#https://github.com/revolunet/create-react-app-circleci/blob/master/.circleci/config.yml
defaults: &defaults
  docker:
  - image: circleci/node:8 #使用node第8版测试

version: 2 #ciecleCI
jobs:
  prepare:
    <<: *defaults
    steps:
    - checkout  #迁出代码
    - restore_cache:  
        keys:
        - v2-dependencies-{{ checksum "package.json" }}  #md5将package.json作为key 创建到缓存并将node_modules缓存 形成快照
    - run: yarn install #安装所有依赖
    - save_cache:   #保存缓存
        paths:
        - node_modules
        key: v2-dependencies-{{ checksum "package.json" }}
    - persist_to_workspace:
        root: .
        paths:
        - node_modules
  build:
    <<: *defaults
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run: yarn build
    - persist_to_workspace:  #持久化 不删除文件
        root: .
        paths:
        - dist
        - package.json
        - LICENSE
        - README.md  #必须有这四个文件才能发布
  test:
    <<: *defaults
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run: yarn ci
    - store_test_results:
        path: test-results
  publish:    #可以自动publish
    <<: *defaults
    steps:
    - attach_workspace:  
        at: .           #将build产生放过来
    - run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN  #设置token 不加的话会一直提示需要认证
    - run: npm publish

workflows:    #让circle ci 知道工作流程 运行顺序
  version: 2
  build_accept_deploy:
    jobs:
    - prepare
    - build:
        requires:
        - test
    - test:
        requires:
        - prepare
    - publish:
        requires:
        - build